###############################################################################
## This script visualizes the attributions generated by explain.py. It focuses
## on the similarities/differences between shap and minshap for the Drosophila
## case study.
###############################################################################

library(tidyverse)
library(patchwork)
library(ggrepel)
library(here)

source(here("case_studies", "src", "R", "visualize.R"))
base <- here("case_studies", "drosophila")
att <- load_attributions(base)
shap <- att$shap
minshap <- att$minshap
meta <- att$meta

theme_set(theme_axiomatic(base_size = 18))

# -- Figure 1: Credit-splitting scatterplot -----------------------------------

feat_summary <- tibble(
    feature = names(shap),
    mean_abs_shap = colMeans(abs(shap)),
    mean_abs_minshap = colMeans(abs(minshap))
)

feat_summary <- feat_summary |>
    mutate(
        ratio = mean_abs_minshap / pmax(mean_abs_shap, 1e-8),
        residual = abs(mean_abs_minshap - mean_abs_shap),
        label = if_else(
            residual > quantile(residual, 0.99) | mean_abs_shap > quantile(mean_abs_shap, 0.99),
            feature,
            NA_character_
        )
    )

p1 <- ggplot(feat_summary, aes(mean_abs_shap, mean_abs_minshap)) +
    geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = axiom_palette$grid) +
    geom_point(size = 1.9, color = axiom_palette$ink) +
    geom_text_repel(aes(label = label), size = 4.5, max.overlaps = 20, show.legend = FALSE) +
    labs(
        x = "Mean |SHAP|",
        y = "Mean |minSHAP|",
        title = "SHAP vs minSHAP feature importance"
    )

ggsave(path(base, "results", "fig_credit_splitting.pdf"), p1, width = 6, height = 4)

# -- Figure 2: Sample waterfall plots, to see attribution differences ---------

pick_samples <- function(meta) {
    pos <- meta |>
        filter(y_true == 1) |>
        arrange(desc(y_pred_prob))
    high <- slice_head(pos, n = 2)
    low <- slice_tail(pos, n = 2)
    bind_rows(high, low)
}

make_bar <- function(row_idx, attr_df, method_label) {
    attribution_barplot(
        row_idx,
        attr_df,
        method_label
    )
}

selected <- pick_samples(meta)
row_indices <- match(selected$sample_idx, meta$sample_idx)

panels <- map(row_indices, function(ri) {
    prob <- meta$y_pred_prob[ri]
    label <- glue::glue("Sample {meta$sample_idx[ri]} (P={formatC(prob, digits = 2, format = 'f')})")
    shap_bar <- make_bar(ri, shap, "SHAP") + ggtitle(label)
    min_bar <- make_bar(ri, minshap, "minSHAP")
    shap_bar | min_bar
})

p2 <- wrap_plots(panels, ncol = 1) +
    plot_annotation(title = "Top features by method")

ggsave(path(base, "results", "fig_sample_panels.pdf"), p2, width = 8, height = 10)

# -- Figure 3: Do we see subgroups across attributions? ------------------------

feat_var <- shap |>
    as.data.frame() |>
    map_dbl(var)
top_features <- names(sort(feat_var, decreasing = TRUE))[1:min(50, ncol(shap))]

shap_mat <- as.matrix(shap[, top_features])

hc_shap <- hclust(dist(shap_mat), method = "ward.D2")
sample_order <- hc_shap$order

heatmap_df <- shap_mat[sample_order, ] |>
    as_tibble() |>
    mutate(sample_pos = row_number()) |>
    pivot_longer(-sample_pos, names_to = "feature", values_to = "attribution")

feat_order <- hclust(dist(t(shap_mat[, top_features])), method = "ward.D2")$order
heatmap_df <- heatmap_df |>
    mutate(feature = factor(feature, levels = top_features[feat_order]))

lim <- max(abs(heatmap_df$attribution))

anno_df <- meta[sample_order, ] |>
    mutate(sample_pos = row_number())

# Predicted probability as an aligned barplot, sharing the heatmap's row order.
p_prob <- ggplot(anno_df, aes(y_pred_prob, sample_pos)) +
    geom_col(fill = axiom_palette$ink, width = 1, orientation = "y") +
    scale_x_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1), expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
    theme_axiomatic(base_size = 18) +
    labs(x = "P(Positive)", y = NULL) +
    theme(
        axis.text.y = element_blank(),
        panel.grid.major.y = element_blank()
    )

p_heat <- ggplot(heatmap_df, aes(feature, sample_pos, fill = attribution)) +
    geom_tile() +
    scale_fill_shap(limits = c(-lim, lim)) +
    scale_y_continuous(expand = c(0, 0)) +
    labs(x = NULL, y = NULL) +
    theme_axiomatic(base_size = 18) +
    theme(
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_blank(),
        panel.grid = element_blank(),
        plot.margin = margin(5, 5, 10, 5)
    )

p3 <- (p_prob + p_heat) +
    plot_layout(widths = c(4, 30)) +
    plot_annotation(title = "SHAP attribution subgroups")

ggsave(path(base, "results", "fig_subgroups.pdf"), p3, width = 13, height = 8)
