name: ni_case_studies
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy>=1.26,<2
  - pandas<3
  - scikit-learn
  - scipy
  - pyarrow
  - pillow
  - pip:
      - numpy<2
      - cvxpy<1.7
      - hydra-core
      - omegaconf
      - torch
      - torchvision
      - huggingface-hub
      - transformers
      - shap
      - knockpy
