defaults:
  - _self_

hydra:
  job:
    chdir: false

seed: 2026

paths:
  data_dir: data
  results_dir: results/importance
  model_path: results/model.pt
  model_source_dir: results/model_source
  sample_meta: results/sample_meta.csv

model:
  batch_size: 256

explain:
# n_samples is the the number of coalitions per selected image and n_background
# rows are used for imputation for each coalition
  n_samples: 2000
  n_background: 10
  target: predicted_label

integrated_gradients:
  n_steps: 4
  eps: 0.0001

local_ttest:
  # we consider only a subsample ("pool") for neighborhood selection
  distance: resnet_final_embedding_l2
  n_pool: 1000
  n_neighbors: 20
  min_group_size: 2

run:
  sample_limit: null
