###############################################################################
## This script visualizes the attributions generated by explain.py. It focuses
## on the similarities/differences between shap and minshap.
###############################################################################

library(tidyverse)
library(ggthemes)
library(patchwork)
library(scico)
library(ggrepel)

source(here::here("case_studies", "src", "R", "visualize.R"))
base <- here::here("case_studies", "tcga_brca")
att <- load_attributions(base)
shap <- att$shap
minshap <- att$minshap
meta <- att$meta

theme_set(theme_economist(base_size = 10))
omic_colors <- c(mrna = "#2b8cbe", mirna = "#e34a33", protein = "#31a354")

parse_omic <- function(feature) {
    str_extract(feature, "^[^_]+")
}

strip_prefix <- function(feature) {
    str_remove(feature, "^(mrna|mirna|protein)__")
}

# -- Figure 1: Credit-splitting scatterplot -----------------------------------

feat_summary <- tibble(
    feature = names(shap),
    mean_abs_shap = colMeans(abs(shap)),
    mean_abs_minshap = colMeans(abs(minshap)),
    omic = parse_omic(feature)
)

feat_summary <- feat_summary |>
    mutate(
        ratio = mean_abs_minshap / pmax(mean_abs_shap, 1e-8),
        residual = abs(mean_abs_minshap - mean_abs_shap),
        label = if_else(
            residual > quantile(residual, 0.99) | mean_abs_shap > quantile(mean_abs_shap, 0.99),
            strip_prefix(feature),
            NA_character_
        )
    )

p1 <- ggplot(feat_summary, aes(mean_abs_shap, mean_abs_minshap, color = omic)) +
    geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "grey50") +
    geom_point(alpha = 0.5, size = 1.2) +
    geom_text_repel(aes(label = label), size = 2.5, max.overlaps = 20, show.legend = FALSE) +
    scale_color_manual(values = omic_colors, name = "Omic") +
    labs(
        x = "Mean |SHAP|",
        y = "Mean |minSHAP|",
        title = "Credit splitting: SHAP vs minSHAP feature importance"
    )

ggsave(file.path(base, "results", "fig_credit_splitting.pdf"), p1, width = 8, height = 6)

# -- Figure 2: Patient waterfall plots, to see attribution differences ---------

pick_patients <- function(meta) {
    ilc <- meta |>
        filter(y_true == 1) |>
        arrange(desc(y_pred_prob))
    high <- slice_head(ilc, n = 2)
    low <- slice_tail(ilc, n = 2)
    bind_rows(high, low)
}

make_bar <- function(row_idx, attr_df, method_label) {
    attribution_barplot(
        row_idx,
        attr_df |> rename_with(strip_prefix),
        method_label
    )
}

selected <- pick_patients(meta)
row_indices <- match(selected$sample_idx, meta$sample_idx)

panels <- map(row_indices, function(ri) {
    prob <- meta$y_pred_prob[ri]
    label <- glue::glue("Patient {meta$sample_idx[ri]} (P={formatC(prob, digits = 2, format = 'f')})")
    shap_bar <- make_bar(ri, shap, "SHAP") + ggtitle(label)
    min_bar <- make_bar(ri, minshap, "minSHAP")
    shap_bar | min_bar
})

p2 <- wrap_plots(panels, ncol = 1) +
    plot_annotation(title = "Top features by attribution: SHAP vs minSHAP")

ggsave(file.path(base, "results", "fig_patient_panels.pdf"), p2, width = 10, height = 12)

# -- Figure 3: Do we see subgoups across attributions? ------------------------

feat_var <- shap |>
    as.data.frame() |>
    map_dbl(var)
top_features <- names(sort(feat_var, decreasing = TRUE))[1:min(50, ncol(shap))]

shap_mat <- as.matrix(shap[, top_features])
minshap_mat <- as.matrix(minshap[, top_features])

hc_shap <- hclust(dist(shap_mat), method = "ward.D2")
hc_min <- hclust(dist(minshap_mat), method = "ward.D2")

k <- 4
meta <- meta |>
    mutate(
        shap_cluster = factor(cutree(hc_shap, k)),
        minshap_cluster = factor(cutree(hc_min, k)),
        cluster_disagree = shap_cluster != minshap_cluster,
        row_order = order(hc_shap$order)
    )

patient_order <- hc_shap$order

heatmap_df <- shap_mat[patient_order, ] |>
    as_tibble() |>
    mutate(patient_pos = row_number()) |>
    pivot_longer(-patient_pos, names_to = "feature", values_to = "attribution") |>
    mutate(feature = strip_prefix(feature))

feat_order <- hclust(dist(t(shap_mat[, top_features])), method = "ward.D2")$order
heatmap_df <- heatmap_df |>
    mutate(feature = factor(feature, levels = strip_prefix(top_features[feat_order])))

lim <- max(abs(heatmap_df$attribution))

p_heat <- ggplot(heatmap_df, aes(feature, patient_pos, fill = attribution)) +
    geom_tile() +
    scale_fill_scico(palette = "berlin", limits = c(-lim, lim), name = "SHAP") +
    labs(x = NULL, y = NULL) +
    theme_economist(base_size = 7) +
    theme(
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size = 5),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()
    )

anno_df <- meta[patient_order, ] |>
    mutate(patient_pos = row_number())

p_label <- ggplot(anno_df, aes(x = 1, y = patient_pos, fill = factor(y_true, labels = c("IDC", "ILC")))) +
    geom_tile() +
    scale_fill_manual(values = c(IDC = "#bdbdbd", ILC = "#e34a33"), name = "True label") +
    theme_void() +
    theme(legend.position = "bottom", legend.key.size = unit(0.3, "cm"))

p_prob <- ggplot(anno_df, aes(x = 1, y = patient_pos, fill = y_pred_prob)) +
    geom_tile() +
    scale_fill_scico(palette = "berlin", name = "P(ILC)") +
    theme_void() +
    theme(legend.position = "bottom", legend.key.size = unit(0.3, "cm"))

p_disagree <- ggplot(anno_df, aes(x = 1, y = patient_pos, fill = cluster_disagree)) +
    geom_tile() +
    scale_fill_manual(values = c(`FALSE` = "white", `TRUE` = "#fdae61"), name = "Cluster\ndisagree") +
    theme_void() +
    theme(legend.position = "bottom", legend.key.size = unit(0.3, "cm"))

p3 <- (p_label | p_prob | p_disagree | p_heat) +
    plot_layout(widths = c(1, 1, 1, 30)) +
    plot_annotation(title = "SHAP attribution subgroups (top 50 features)")

ggsave(file.path(base, "results", "fig_subgroups.pdf"), p3, width = 14, height = 8)
